<? $title = 'Add new item'; ?>
<? $this->headTitle($title); ?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php

$name_elem = $form->get('name');
$name_elem->setAttribute('class', 'form-control');
$name_elem->setAttribute('placeholder', 'Name');

$submit_elem = $form->get('submit');
$submit_elem->setAttribute('class', 'btn btn-primary pull-right');

$form->setAttribute('action', $this->url('items', ['action' => 'add']));
$form->prepare();

?>

<div class="col-md-offset-3 col-md-6 well">
    <?= $this->form()->openTag($form); ?>
    <div class="form-group">
        <?= $this->formLabel($name_elem) ?>
        <?= $this->formElement($name_elem) ?>
        <?= $this->formElementErrors()->render($name_elem, ['class' => 'error']) ?>
    </div>

    <?php
        echo $this->formSubmit($submit_elem);
        echo $this->form()->closeTag();
    ?>
</div>