<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Test application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">Test application</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?= $this->url('items', ['action' => 'add']) ?>">Add item</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->flashMessenger()->setMessageOpenFormat('<div%s>')->setMessageCloseString('</div>')->render('success', ['alert', 'alert-success']); ?>
            <?= $this->content ?>
        </div>

        <div class="container footer text-center">
            <a href="https://beejee.ru"><img src="<?= $this->basePath('img/pobeda.jpeg') ?>" class="img-responsive winner-banner" alt="Winner"></a>
        </div>
    </body>
</html>
